### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by sdhlucny** [bulldog-bots/rover_kit#1]
- [x] Implement Drive class in drive.cpp.
- [ ] Review and test Drive class.
- [ ] Write ultrasonic.h (specify classes, functions, etc)
- [ ] Write infrared.h (specify classes, functions, etc)
- [ ] Write servo.h (specify classes, functions, etc)
- [ ] Write optical.h (specify classes, functions, etc)
